#!/bin/bash


# --- Configuration ---
WALLPAPER_DIR="$HOME/.config/hyprWalls" 
HYPRLAND_CONF_DIR="$HOME/.config/hypr/hyprland.conf"
HYPRLOCK_CONF_DIR=" $HOME/.config/hypr/hyprlock.conf"
RIVER_CONF_DIR="$HOME/.config/river/init"
NIRI_CONF_DIR="$HOME/.config/niri/config.kdl"
# --- End Configuration ---


# Find all image files (jpg, jpeg, png) in the directory
# You can add more extensions if needed (e.g., "*.webp")
IMAGE_FILES=$(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \))

# Check if any images were found
if [ -z "$IMAGE_FILES" ]; then
    echo "No images found in $WALLPAPER_DIR"
    exit 1
fi

# Pipe the list of images into fzf.
# --preview: specifies the command to run for the preview window.
#   '{}' is a placeholder for the currently selected line (the image path).
#   'chafa -s 50x50 --fill symbols "{}"' creates a 50x50 character preview.
#   Adjust the size ('-s 50x50') to fit your preference.
SELECTED_IMAGE=$(echo "$IMAGE_FILES" | fzf \
   --delimiter / --with-nth -1 \
   --layout=reverse --border=rounded --margin=1,1 \
   --color=bg+:-1,fg:7,fg+:7,hl:4,hl+:4,info:3,prompt:2,pointer:5,marker:6,spinner:1,border:8 \
   --prompt="   Select Image ❯ " --pointer="▶ " --marker="✓ " \
   --preview 'kitty +kitten icat --clear --transfer-mode=memory --stdin=no --place={$FZF_PREVIEW_COLUMNS}x{$FZF_PREVIEW_LINES}@0x0 {}' \
   --preview-window=right:40%:wrap \
   --bind "ctrl-c:abort")

# Exit if no image was selected (e.g., user pressed Esc or Ctrl-C)
if [ -z "$SELECTED_IMAGE" ]; then
	echo "No Image Selected!"
    exit 0
fi


cp $SELECTED_IMAGE /usr/share/sddm/themes/Andromeda-plasma-6
cp /usr/share/sddm/themes/Andromeda-plasma-6/theme.conf.user /tmp
NAME_IMG=$(echo "$SELECTED_IMAGE" |cut -d/ -f6)
sed -i "s|background =.*|background = $NAME_IMG|" /tmp/theme.conf.user
cat /tmp/theme.conf.user > /usr/share/sddm/themes/Andromeda-plasma-6/theme.conf.user

if [[ $DESKTOP_SESSION == "niri" ]]; then
	qs -c noctalia-shell ipc call wallpaper set $SELECTED_IMAGE
	wal -i $SELECTED_IMAGE -n -q
	sed -i "s|wall .*|wall \"$SELECTED_IMAGE\"|" $NIRI_CONF_DIR
	sudo cp $SELECTED_IMAGE /usr/share/sddm/themes/pixie/assets/background.jpg

elif [[ $DESKTOP_SESSION == "mango" ]]; then
	qs -c noctalia-shell ipc call wallpaper set $SELECTED_IMAGE
	wal -i $SELECTED_IMAGE -n -q
	sed -i "s|wall .*|wall \"$SELECTED_IMAGE\"|" $NIRI_CONF_DIR
	
elif [[ $DESKTOP_SESSION == "river" ]]; then
	sed -i "s|wall=.*|wall=$SELECTED_IMAGE|" $RIVER_CONF_DIR
	bash $RIVER_CONF_DIR
	~/.config/mako/update-theme.sh
else
	sed -i "s|\$wall =.*|\$wall = $SELECTED_IMAGE|"  $HYPRLAND_CONF_DIR
	~/.config/mako/update-theme.sh
fi

sed -i "s|\$wall =.*|\$wall = $SELECTED_IMAGE|"  $HYPRLOCK_CONF_DIR	

clear
fastfetch
